name: core

on:
  push:
    branches:
      - main
    paths:
      - 'platformio/**'
      - 'scripts/**'
      - 'tests/**'
      - '**/core.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.11]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          submodules: "recursive"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Core System Info
        run: |
          tox -e py

      - name: Python Lint
        if: ${{ matrix.python-version != '3.6' }}
        run: |
          tox -e lint

      - name: Integration Tests
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          tox -e testcore
