name: deployment

on:
  push:
    branches:
      - main
    paths:
      - 'platformio/**'
      - 'scripts/**'
      - 'tests/**'
      - '**/deployment.yml'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox wheel

      - name: Deployment Tests
        env:
          TEST_EMAIL_LOGIN: ${{ secrets.CI_MAIL_NAME }}
          TEST_EMAIL_PASSWORD: ${{ secrets.CI_MAIL_PASSWORD }}
          TEST_EMAIL_IMAP_SERVER: ${{ secrets.CI_MAIL_IMAP_SERVER }}
        run: |
          tox -e testcore

      - name: Build Python source tarball
        # run:  python setup.py sdist bdist_wheel
        run:  python setup.py sdist

      - name: Publish package to PyPI
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PIO_TOKEN }}
