name: examples

on:
  push:
    branches:
      - main
    paths:
      - 'platformio/**'
      - 'examples/**'
      - '**/examples.yml'
  schedule:
    - cron: "30 23 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      PIO_INSTALL_DEVPLATFORM_OWNERNAMES: "platformio"
      PIO_INSTALL_DEVPLATFORM_NAMES: "atmelavr,atmelmegaavr,atmelsam,espressif32,nordicnrf52,raspberrypi,ststm32,teensy"

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          # Free space
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
          tox -e testexamples

      - name: Run on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          df -h
          tox -e testexamples

      - name: Run on Windows
        if: startsWith(matrix.os, 'windows')
        env:
          PLATFORMIO_CORE_DIR: C:/pio
          PLATFORMIO_WORKSPACE_DIR: C:/pio-workspace/$PROJECT_HASH
        run: |
          tox -e testexamples
