name: platforms

on:
  push:
    branches:
      - main
    paths:
      - 'platforms/**'
      - '**/platforms.yml'
  # schedule:
  #   - cron: "30 23 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "esp32"
          - "rp2040"
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7, 3.9, 3.11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          submodules: "recursive"

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}


      - name: Test on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          python -m pip install --upgrade pip
          pip install -U .
          pio pkg install -g -p platforms/${{ matrix.platform }}
          pio pkg list

      - name: Test on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          python -m pip install --upgrade pip
          pip install -U .
          pio pkg install -g -p platforms/${{ matrix.platform }}
          pio pkg list

      - name: Test on Windows
        if: startsWith(matrix.os, 'windows')
        env:
          PLATFORMIO_CORE_DIR: C:/pio
          PLATFORMIO_WORKSPACE_DIR: C:/pio-workspace/$PROJECT_HASH
        run: |
          python -m pip install --upgrade pip
          pip install -U .
          pio pkg install -g -p platforms/${{ matrix.platform }}
          pio pkg list
